Script for splitting large zip files
UiPath/du-customer-scripts pull request #2
Opened 2021-07-27 15:14 UTC by cezara98t

2021-07-27 19:46 UTC, bogdancondurache requested changes

2021-07-27 19:46 UTC, bogdancondurache commented on datamanager/splitLargeZip/splitZip.py
> +ONEGB = 1000000000
```suggestion
ONE_GB = 2 ** 30
```

2021-07-27 19:46 UTC, bogdancondurache commented on datamanager/splitLargeZip/splitZip.py
> +    processZip(args.path)
try/except and proper error message if it fails

2021-07-27 19:46 UTC, bogdancondurache commented on datamanager/splitLargeZip/splitZip.py
> +    splitZip.py --path C:\\path\\to\\zip
let's use snake_case for both variables and file names as this is Python standard:
https://www.python.org/dev/peps/pep-0008/
very short version: https://visualgit.readthedocs.io/en/latest/pages/naming_convention.html

2021-07-27 19:46 UTC, bogdancondurache commented on datamanager/splitLargeZip/splitZip.py
> +class configs:
```suggestion
class Configs:
```

2021-07-27 19:46 UTC, bogdancondurache commented on datamanager/splitLargeZip/splitZip.py
> +    path_to_split = ""
```suggestion
    schema_path: Path  = Path()
    split_path: Path = Path()
```

2021-07-27 19:46 UTC, bogdancondurache commented on datamanager/splitLargeZip/splitZip.py
> +    start_size = 0  # size of schema and split file
```suggestion
    start_size: int = 0  # size of schema and split file
```

2021-07-27 19:46 UTC, bogdancondurache commented on datamanager/splitLargeZip/splitZip.py
> +ONEGB = 1000000000
or maybe even better: `ONE_GB = 2 ** 30 - 1`

2021-07-27 19:46 UTC, bogdancondurache commented on datamanager/splitLargeZip/splitZip.py
> +    parser = argparse.ArgumentParser()
```suggestion
    parser = argparse.ArgumentParser(description="Split a dataset into multiple archives.")
```

2021-07-27 19:46 UTC, bogdancondurache commented on datamanager/splitLargeZip/splitZip.py
> +    parser.add_argument("--path", help="the path of the zip")
```suggestion
    parser.add_argument("--path", help="the path to the zip file")
```

2021-07-27 19:46 UTC, bogdancondurache commented on datamanager/splitLargeZip/splitZip.py
> +    splitZip.py --path C:\\path\\to\\zip
```suggestion
    split_zip.py --path C:\\path\\to\\import\\archive.zip
```

2021-07-27 19:46 UTC, bogdancondurache commented on datamanager/splitLargeZip/splitZip.py
> +def processZip(path):
```suggestion
def process_zip(path: Path):
```

2021-07-27 19:46 UTC, bogdancondurache commented on datamanager/splitLargeZip/splitZip.py
> +    processZip(args.path)
```suggestion
    processZip(Path(args.path))
```

2021-07-27 19:46 UTC, bogdancondurache commented on datamanager/splitLargeZip/splitZip.py
> +    processZip(args.path)
```suggestion
    process_zip(args.path)
```

2021-07-27 19:46 UTC, bogdancondurache commented on datamanager/splitLargeZip/splitZip.py
> +                path.name: path for path in list(Path(temp_zip_contents + "/" + path.rstrip(".zip")).iterdir())
```suggestion
                path.name: path for path in Path(temp_zip_contents) / path.stem).iterdir()
```
you don't need list conversion as `for ... in` knows to user generators and iterators. Also if `path` would be of type Path you can use `.stem` instead os rstrip which is more hackish. Path joining can be done even as in the suggestion with `/` or with `.joinpath()`.
Please check https://docs.python.org/3/library/pathlib.html - it also has alternatives from using strings to using Path objects. Also this for iterators and generators: https://anandology.com/python-practice-book/iterators.html

2021-07-27 19:46 UTC, bogdancondurache commented on datamanager/splitLargeZip/splitZip.py
> +            configs.start_size += os.stat(configs.path_to_schema).st_size
```suggestion
            configs.start_size += configs.path_to_schema.stat().st_size
```
if this is Path object

2021-07-27 19:46 UTC, bogdancondurache commented on datamanager/splitLargeZip/splitZip.py
> +            configs.start_size += os.stat(configs.path_to_split).st_size
same as above

2021-07-27 19:46 UTC, bogdancondurache commented on datamanager/splitLargeZip/splitZip.py
> +            splitFiles(dictionary_paths["images"], dictionary_paths["latest"], temp_zip_contents)
```suggestion
            split_files(dictionary_paths["images"], dictionary_paths["latest"], temp_zip_contents)
```

2021-07-27 19:46 UTC, bogdancondurache commented on datamanager/splitLargeZip/splitZip.py
> +def splitFiles(images_path, latest_path, temp_zip):
```suggestion
def split_files(images_path: Path, latest_path: Path, temp_zip: Type?):
```

2021-07-27 19:46 UTC, bogdancondurache commented on datamanager/splitLargeZip/splitZip.py
> +    dict_latest_paths = {path.name.strip(".json"): path for path in list(Path(latest_path).iterdir())}
`.stem`

2021-07-27 19:46 UTC, bogdancondurache commented on datamanager/splitLargeZip/splitZip.py
> +        size = os.stat(dict_image_paths[path_name]).st_size + os.stat(dict_latest_paths[path_name]).st_size
`.stat().st_size`

2021-07-27 19:46 UTC, bogdancondurache commented on datamanager/splitLargeZip/splitZip.py
> +def writeOneZip(temp_zip, image_list, archive_number):
```suggestion
def write_one_zip(temp_zip, image_list, archive_number):
```
and types please

2021-07-27 19:46 UTC, bogdancondurache commented on datamanager/splitLargeZip/splitZip.py
> +                for image_path in image_list:
could you use `zip()` for these?

2021-07-27 19:46 UTC, bogdancondurache commented on datamanager/splitLargeZip/splitZip.py
> +            os.path.join(root, configs.path_to_schema),
let's use pathlib instead :)

2021-07-27 19:46 UTC, bogdancondurache commented on datamanager/splitLargeZip/splitZip.py
> +    with open(new_split_name, "w", newline="") as writeFile:
```suggestion
    with open(new_split_name, "w", newline="") as write_file:
```

2021-07-28 05:27 UTC, misupantea-uipath approved these changes

2021-07-28 05:27 UTC, misupantea-uipath commented on datamanager/splitLargeZip/splitZip.py
> +    dict_latest_paths = {path.name.strip(".json"): path for path in list(Path(latest_path).iterdir())}
`archive_number`

2021-07-28 09:33 UTC, misupantea-uipath commented on datamanager/splitLargeZip/split_zip.py
> +    dict_image_paths = {path.name: path for path in list(Path(images_path).iterdir())}
`image_paths`

2021-07-28 09:33 UTC, misupantea-uipath commented on datamanager/splitLargeZip/split_zip.py
> +    for image_name in dict_image_paths:
enumerate key-value pairs?

2021-07-28 09:33 UTC, misupantea-uipath commented on datamanager/splitLargeZip/split_zip.py
> +def write_one_zip(folder_contents_path: str, image_names: list, archive_number: int):
`write_one_zip` -> `create_archive`

2021-07-28 09:33 UTC, misupantea-uipath commented on datamanager/splitLargeZip/split_zip.py
> +    archive_number = 1
`archive_count`

2021-07-28 09:33 UTC, misupantea-uipath commented on datamanager/splitLargeZip/split_zip.py
> +def write_one_zip(folder_contents_path: str, image_names: list, archive_number: int):
`archive_number` -> `suffix`

2021-07-28 09:33 UTC, misupantea-uipath commented on datamanager/splitLargeZip/split_zip.py
> +    with zipfile.ZipFile("splitArchive" + str(archive_number) + ".zip", "w") as zip_handle:
`"splitArchive"` -> maybe use the original archive name

Use `_` for suffixing

2021-07-28 09:33 UTC, misupantea-uipath commented on datamanager/splitLargeZip/split_zip.py
> +                    if image_name in file:
Add a comment here to point out that both the image and related metadata file will be picked up for writing due to the `in` check

2021-07-28 09:33 UTC, misupantea-uipath commented on datamanager/splitLargeZip/split_zip.py
> +    temp_split_path = str(Configs.split_path) + "_"
Use the `suffix` param from `create_archive` to generate the `temp_split_path`, that way we can debug splits easier

2021-07-29 11:26 UTC, misupantea-uipath approved these changes

2021-07-29 11:56 UTC, bogdancondurache approved these changes

2021-07-29 11:56 UTC, merged